### ISSUE TITLE
The packaged js will have all the css strings

### ISSUE THREAD

**Issue by fanhaoyuan** [underfin/vite-plugin-vue2#37]
dev:
```js
// main,js
import "./test2.css";
```
```css
.test {
    position: absolute;
}

.test2 {
    position: relative;
}
```

built:
```js
//index.[hash].js

var test = ".test {\n  position: absolute;\n}\n";
var test2 = ".test2 {\n    position: relative;\n}";
```

I don't want the global style to be reflected in the js after packing, because it's a useless string, which makes the js package big.
